# hivemq/hivemq4:4.40.0
FROM hivemq/hivemq4@sha256:df3c515c887094b7c58dbfe51eef0e820a93e8740cdaf9f484c2e03ce40e1c79

# Add extensions
COPY hivemq-sparkplug-extension /opt/hivemq/extensions/hivemq-sparkplug-extension
