# hivemq/hivemq4:4.40.0
FROM hivemq/hivemq4@sha256:5f0bd8f3eea816ab43ffcee5629601bcadca042514b5b1bd23f2576468515044

# Add extensions
COPY hivemq-sparkplug-extension /opt/hivemq/extensions/hivemq-sparkplug-extension
