version: '2'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_ORG: hivemq
      DOCKER_INFLUXDB_INIT_BUCKET: hivemq
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin888
      INFLUXDB_DB: hivemq
    ports:
      - "8086:8086"
    volumes:
      - influxdb-volume:/var/lib/influxdb

volumes:
  influxdb-volume: