ARG HIVEMQ_VERSION=4.5.3

FROM hivemq/hivemq4@sha256:b8ece58495da84e3b3c5ec4aa5b954c06132f2876063fe2a7df73155c6c180ec

# Add extensions
COPY hivemq-sparkplug-extension /opt/hivemq/extensions/hivemq-sparkplug-extension
